### ISSUE TITLE
کانال های کانفیگ دزدی

### ISSUE THREAD

**Issue by DooMaria** [yebekhe/TelegramV2rayCollector#10]
ممنون از تیم 
ircfspace
 و 
yebekhe
 
یک مشکل بسیار بزرگ هست
بعضی از کانال هایی که برای کانفیگ اضافه شدن کانفیگ های بقیه اسمش عوض میکنن و به اسم رایگان داخل کانال و سایت تبلیغ میکنند
کاشکی قبل از تایید هر کانال صحت اون اون کانال برسی بشه

**Comment by yebekhe** [comment]
امکان صحت سنجی و پیدا کردن کانال مبدا هر کانفیگ وجود نداره
مکانیسمی در این باره ایجاد شده که تا حد امکان از تکراری بودن کانفیگ ها جلوگیری میکنه
اما اگه تو شرایط فعلی بخوایم منابع موجود رو فیلتر کنیم جز یک یا دو کانال باید قید اکثر اون ها رو بزنیم که غیر ممکنه
امکان بررسی تک به تک در حال حاضر برای شخص من وجود نداره
برای کانفیگ های غیر فعال هم اتومات چک میشه قبل از اینکه وارد لینک سابسکرایب بشه و  کانفیگ هایی که متصل هست انتخاب میشن ممکنه روی نت شما فطع و نت دیگر وصل باشه
من پلیس کانال های تلگرام نیستم و دنبال اتصال مردمم

**Comment by DooMaria** [comment]
1- لطفا درخواست کمک کن!
 افراد زیادی توی این حوزه به دنبال فعالیت هستند 
۲- کانفیگ هارو با چندین نت تست میکنم ( اگه کانفیگ یا سرور پینگ نده با سرور های خارج از ایران تست میکنم که بهونه نت ایران روش نباشه
۳- دمت گرم تا اینجا ، من نگفتم پلیس باش  ولی با چک نکردن کانال ها همزمان ضرر به افرادی که دارن هزینه میکنن و ازشون دزدی میشه نزن
