### ISSUE TITLE
معرفی کانال 

### ISSUE THREAD

**Issue by parsashonam** [yebekhe/TelegramV2rayCollector#11]
درود، فکر کنم منم بتونم کمک کنم، به امید اینترنت آزاد ✌🏼💙

https://t.me/Parsashonam

**Comment by amirmohammad-mohammad-88** [comment]
کانال های خوب فیلتر برای جم آوری! 

https://t.me/VPNs_ir
https://t.me/fastvpn_server
https://t.me/free1_vpn
https://t.me/OnBashBaw
https://t.me/SafeNetIR
