### ISSUE TITLE
باگ json

### ISSUE THREAD

**Issue by amazon-mix** [yebekhe/TelegramV2rayCollector#12]
سلام فایل json باگ داره و فقط vmess درست کار میکنه vless و realityو trojan مشکل داره  وقتی کپی میشه  توی برنامه v2ray نصف تنظیمات خالیه

**Comment by yebekhe** [comment]
خب فایل json برای این نیست شما بری از توش لینکو کپی کنی :/ 
اون خروجی باید json decode بشه بعد  urlencode بشه :/

**Comment by yebekhe** [comment]
وبسایت https://ircfspace.github.io/tconfig/ از همین خروجی استفاده کردن و مشکلی گزارش نشده
به هر صورت چک میکنم مجدد
