### ISSUE TITLE
معرفی کانال

### ISSUE THREAD

**Issue by Mohsenone2525** [yebekhe/TelegramV2rayCollector#13]
اینا کانال اییه که میشناسم. خیلیاش تو بات شما هست. 
دمت گرم رفیق❤️
@v2rayngzendegimamad

@Outlinev2rayNG

@oneclickvpnkeys

@shadowsocksshop

@VpnRaya

t.me/Maznet

@VPN_VIP_NOR

prrofile_purple@

@prrofile_purple

@ghalagyann

@customv2ray

@soscw

@f_u_c_k_of_f

@v2Ray1_ng

Napsternetpro@

@Napsternetpro

@ConfigProBot

T.me/PainB0y

@AntiMeliNet

@ParaphDev

@napsVPNHTcus

T.me/mojogify

@shadowsocksshop

@vpnmasi

@V2ray_Team

@kutoproxy

@vpn_ocean

@nofiltering2

t.me/PrivateVPNs

https://t.me/vipir_vpn

**Comment by mohammadrivadeh** [comment]
> اینا کانال اییه که میشناسم. خیلیاش تو بات شما هست. 
> دمت گرم رفیق❤️
> @v2rayngzendegimamad
> 
> @Outlinev2rayNG
> 
> @oneclickvpnkeys
> 
> @shadowsocksshop
> 
> @VpnRaya
> 
> t.me/Maznet
> 
> @VPN_VIP_NOR
> 
> prrofile_purple@
> 
> @prrofile_purple
> 
> @ghalagyann
> 
> @customv2ray
> 
> @soscw
> 
> @f_u_c_k_of_f
> 
> @v2Ray1_ng
> 
> Napsternetpro@
> 
> @Napsternetpro
> 
> @ConfigProBot
> 
> T.me/PainB0y
> 
> @AntiMeliNet
> 
> @ParaphDev
> 
> @napsVPNHTcus
> 
> T.me/mojogify
> 
> @shadowsocksshop
> 
> @vpnmasi
> 
> @V2ray_Team
> 
> @kutoproxy
> 
> @vpn_ocean
> 
> @nofiltering2
> 
> t.me/PrivateVPNs
> 
> https://t.me/vipir_vpn

https://t.me/frev2ray

**Comment by mohammadrivadeh** [comment]
https://t.me/frev2ray

**Comment by yebekhe** [comment]
با تشکر 
لطفا موارد غیر تکراری رو تفکیک کنید و مجدد ارسال کنید
