### ISSUE TITLE
ربات v2ray

### ISSUE THREAD

**Issue by Sepehr0Day** [yebekhe/TelegramV2rayCollector#14]
سلام
یه بات اوردم بالا توی تلگرام که میاد تموم کانفیگ های موجود توی همین مخزن رو تیو تلگرام برای سهولت دسترسی قرار میده
امیدوارم صاحب این مخزن راضی باشه(ازشون نام بردم توی پین چنل)

ادرس چنل :
https://t.me/V2RayVPNFree

**Comment by yebekhe** [comment]
سلام ، موفق باشید 
بیشتر از من تامین کنندگان بایستی رضایت داشته باشن ❤️
هر گونه مشکل یا سوالی داشتید هم میتونید مطرح کنید ✋🏻
