### ISSUE TITLE
معرفی کانال

### ISSUE THREAD

**Issue by AliAlmasi** [yebekhe/TelegramV2rayCollector#15]
سلام میتونین این کانال هارو هم اضافه کنید.  
`@init1984`
`@beiten`
`@glysit`
`@cyru44_ch4`
`@prossh`
اگه موارد دیگه‌ای هم پیدا کنم از همین ایشو بهتون اطلاع میدم.  
متشکرم.

**Comment by yebekhe** [comment]
تشکر 
فقط لطفا ابتدا لیست کانال ها رو چک کنید و غیرتکراری ها رو ارسال کنید
