### ISSUE TITLE
اصلاح در get_data.php

### ISSUE THREAD

**Issue by HadiDastangoo** [yebekhe/TelegramV2rayCollector#16]
سلام.
ضمن تشکر و قدردانی از زحماتتون، در خط 60 فایل [modules/get_data.php](https://github.com/yebekhe/TelegramV2rayCollector/blob/main/modules/get_data.php) به نظر می‌رسه کد باید از:

```php
$config = substr($config, 0, $config, "<br/>");
```

به:

```php
$config = substr($config, 0, strpos($config, "<br/>"));
```

اصلاح بشه.
موفق باشید.

**Comment by yebekhe** [comment]
با تشکر از دقت شما 
کاملا صحیح اشاره کردید اصلاح شد ❤️
