### ISSUE TITLE
add clash support for config lists

### ISSUE THREAD

**Issue by Mahgozar** [yebekhe/TelegramV2rayCollector#2]

**Comment by yebekhe** [comment]
it will be added soon

**Comment by coldwater-10** [comment]
کانفیگ کلش متا هم درست کن تا vless و ریلیتی هارو هم داشته باشه

**Comment by coldwater-10** [comment]
کانفیگ کلش متا هم درست کن تا vless و ریلیتی هارو هم داشته باشه

**Comment by sh-vp** [comment]
مگه Riality روی متا کار میکنه ؟

> کانفیگ کلش متا هم درست کن تا vless و ریلیتی هارو هم داشته باشه

**Comment by yebekhe** [comment]
> کانفیگ کلش متا هم درست کن تا vless و ریلیتی هارو هم داشته باشه

اصلن پروژه رو چک میکنید قبل ثبت issue؟ کانفیگ متا هست داخل لیست لینک های سابسکرایب

**Comment by coldwater-10** [comment]
> > کانفیگ کلش متا هم درست کن تا vless و ریلیتی هارو هم داشته باشه
> 
> اصلن پروژه رو چک میکنید قبل ثبت issue؟ کانفیگ متا هست داخل لیست لینک های سابسکرایب

اره اون برا قبله اون موقع نداشت

**Comment by coldwater-10** [comment]
> مگه Riality روی متا کار میکنه ؟
> 
> > کانفیگ کلش متا هم درست کن تا vless و ریلیتی هارو هم داشته باشه

آره
