### ISSUE TITLE
اضافه کردن سابسکریپشن reality و xlts-rprx-vision

### ISSUE THREAD

**Issue by abb021** [yebekhe/TelegramV2rayCollector#20]
سلام
من به شخصه با شاتل و ایرانسل فقط با ریالیتی و مخصوصا فلو xlts-rprx-vision میتونم وصل شم. اگه یک سابسکریپشن جدا برای کانفیگ های ریالیتی و ویژن اضافه بشه بنظرم خیلی میتونه مفید باشه، با یه فیلتر ساده روی لینک های کانفیگ ها میشه کانفیگای ریالیتی و xlts-rprx-vision رو تشخیص داد.

**Comment by EndermanCo** [comment]
ساب ریلیتی در صفحه اصلی هست:
https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/reality

**Comment by aetoray** [comment]
ساب ریلیتی در صفحه اصلی هست:
https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/reality

**Comment by Saeed2640153** [comment]
عالیه ریالیتی
