### ISSUE TITLE
کانال جدید

### ISSUE THREAD

**Issue by orinoog** [yebekhe/TelegramV2rayCollector#24]
https://t.me/Royalping_ir 
https://t.me/v2rayng_vpnrog
سلام اگر این کانالا بدرد میخوره اد برنین

**Comment by holms2012** [comment]
https://t.me/ConfigsHUB

**Comment by elena1365** [comment]
https://t.me/VPNS_IR

**Comment by Hojatrafiee** [comment]
![image](https://github.com/yebekhe/TelegramV2rayCollector/assets/123059567/8a9cd6b3-0b07-4026-b6df-b6ba8dcf227c)

خطای چه دوستان🙏
