### ISSUE TITLE
لیست کامل کانفیگ های سالم

### ISSUE THREAD

**Issue by mozilla-firefox** [yebekhe/TelegramV2rayCollector#26]
سلام
لیست موجود در حال حاضر فقط 200 کانفیگ برتر رو میزاره، خیلی خوبه اما لطفا در کنارش لیست کامل از کانفیگ های سالم موجود بزارید
با تشکر

**Comment by yebekhe** [comment]
200 کانفیگ برتر نداریم اینجا ، تو هر اپدبت لیت کانفیگ های سالم قرار میگیره فقط

**Comment by hwyedba4** [comment]
> 200 کانفیگ برتر نداریم اینجا ، تو هر اپدبت لیت کانفیگ های سالم قرار میگیره فقط

سالم بودنش چه جور مشخص میشه؟

**Comment by yebekhe** [comment]
باز بودن آیپی و پورت سرور
