### ISSUE TITLE
معرفی کانال

### ISSUE THREAD

**Issue by EndermanCo** [yebekhe/TelegramV2rayCollector#27]
https://t.me/rxv2ray
https://t.me/Capital_NET
https://t.me/VpnFreeSec
https://t.me/AmirTechno_Service
https://t.me/OPV2ray
https://t.me/Vpn_Mikey
https://t.me/tehron98
https://t.me/IRAN_FOX
https://t.me/lightning6
https://t.me/shh_proxy
https://t.me/WebShecan
https://t.me/FoxNim
https://t.me/lagvpn1
https://t.me/fv2ray

با آخرین لیستی که توی تلگرام بود مطابقت دادم و هیچکدوم از کانالا نبودن.

**Comment by yebekhe** [comment]
ممنون اضافه میشن حتما
