### ISSUE TITLE
Clash.Meta Reality format problematic reality-opts config

### ISSUE THREAD

**Issue by LeeCenY** [yebekhe/TelegramV2rayCollector#29]
Clash.Meta Reality format： https://wiki.metacubex.one/config/proxies/vless/

**Comment by yebekhe** [comment]
Im working on it , and it will be fixed but , any way i think meta core have problem with reality because in my rests application carshed when testing lantency

**Comment by coldwater-10** [comment]
چرا پروکسی های دونیت شده به کانفیگای کلش و کلش متا اضافه نمیشه
