### ISSUE TITLE
کانال کانفیگ رایگان

### ISSUE THREAD

**Issue by Mahdikhm** [yebekhe/TelegramV2rayCollector#3]
این کانال کانفیگ های رایگان خوبی ارسال می کنه: 
v2pedia@
https://t.me/V2pedia

**Comment by yebekhe** [comment]
ممنون اضافه میشه حتما

**Comment by alexfurd1378** [comment]
این کانال هم کانفیگ هاش عالیه 
https://t.me/DarkVPNpro

**Comment by yebekhe** [comment]
تشکر اضافه شدن
