### ISSUE TITLE
اختصاص لینک ساب برای نکوری

### ISSUE THREAD

**Issue by Graveyard9988** [yebekhe/TelegramV2rayCollector#39]
هیچ یک از لینک های ساب سینگ باکس با نکوباکس در نرم افزار nekoray ایمپورت نمی شود

لطفا نسبت به حل این مشکل اقدام کنید

سپاس

**Comment by yebekhe** [comment]
چنین قابلیتی برای نکوری تعریف نشده 
سپاس
