### ISSUE TITLE
تغییر ادرس geoip.db لینک اشتراک

### ISSUE THREAD

**Issue by Graveyard9988** [yebekhe/TelegramV2rayCollector#45]
درود

لطفا ادرس فایل geoip.db اصلی رو در لینک ساب جایگزین مورد فعلی کنید:
https:\/\/github.com\/MiSaturo\/sing-box-geoip-ir\/releases\/latest\/download\/geoip.db

سپاس از زحمات شما

**Comment by Graveyard9988** [comment]
*****https:\/\/github.com\/MiSaturo\/sing-box-geoip-ir\/releases\/latest\/download\/geoip.db****

**Comment by Graveyard9988** [comment]
ادرس فایل نامبرده دارای geoip:private هم می باشد (ایپی لاگین مودم ها و روتر ها) اما لینک فعلی فقط geoip:ir را داراست

**Comment by Hojatrafiee** [comment]
![image](https://github.com/yebekhe/TelegramV2rayCollector/assets/123059567/666f0173-ef6c-4d3f-aa7d-4ac97aabd476)

**Comment by Hojatrafiee** [comment]
سلام استاد خطای چیه؟
