### ISSUE TITLE
حل مشکل اررور های سینگ باکس

### ISSUE THREAD

**Issue by Graveyard9988** [yebekhe/TelegramV2rayCollector#47]
درود
دامنه DoH بیت دفندر در برخی اپراتور ها فیلتر هستش
چنانچه کاربری برای اولین بار singbox را نصب کند، به خاطر DoH فیلترشده، نمی تواند geo فایل ها را دانلود کند
راهکار:
لطفا dns های موجود در لینک سابسکرایب را به 8.8.8.8 و 8.8.4.4 تغییر دهید که مشکل دانلود geo فایل ها و اررور های مربوطه رفع شود

سپاس

**Comment by sae13** [comment]
![Screenshot_20231018-192416_sing-box_20231021084013](https://github.com/yebekhe/TelegramV2rayCollector/assets/17175994/258413c4-0248-4ff4-83cd-377b7d0bbd49)


این خطا بخاطر همینه؟

**Comment by Graveyard9988** [comment]
به خاطر فیلتر بودن DoH هستش
اگر دی ان اس عددی جایگزین بشه،‌درست میشه
