### ISSUE TITLE
معرفی کانال تلکرام

### ISSUE THREAD

**Issue by AmirHossein02** [yebekhe/TelegramV2rayCollector#5]
سلام 
این کانال تلگرام هم کانفیگ می‌ذاره
https://t.me/azadi_az_inja_migzare

**Comment by AmirHossein02** [comment]
این کانال هم همینطور
@vpnstable_admin

**Comment by alexfurd1378** [comment]
این کانال هم میزاره رایگان
https://t.me/DarkVPNpro

**Comment by yebekhe** [comment]
ممنون اضافه شدن به لیست کانال ها

**Comment by elyasph** [comment]
درود
https://t.me/Outline_Vpn
https://t.me/Proxy_PJ
https://t.me/prrofile_purple
این سه تا کانال کانفیگ های خوبی میزارن

**Comment by amirmohammad-mohammad-88** [comment]
سلام کانال های زیر هم هم میزارن مرسی ازتون خیلی دمتون گرم! 
https://t.me/SafeNetIR
https://t.me/SafeNet_Server
https://t.me/free1_vpn
https://t.me/VPNs_ir
https://t.me/narco_nett
