### ISSUE TITLE
Problem with the subconverter

### ISSUE THREAD

**Issue by demarcush** [yebekhe/TelegramV2rayCollector#53]
Software: Clash for Android
Version: 2.5.12

Problem:
facing this during initialization 
![image](https://github.com/yebekhe/TelegramV2rayCollector/assets/146051763/1f5ccec0-2e8b-447e-8bbb-d805e97c8b3d)

and the culprit seems to be this one:
```
- {"name":"رایگان | VMESS | @FreakConfig | RU🇷🇺 | 0️⃣1️⃣ | 3️⃣4️⃣","type":"vmess","server":"141.98.233.36","port":8443,"cipher":"auto","uuid":"24315c24-6af2-4f60-853c-72edc04a0bd7","alterId":0,"tls":false,"skip-cert-verify":true,"network":"grpc","grpc-opts":{"grpc-service-name":"","grpc-mode":"gun"},"client-fingerprint":"chrome"}
```

Also, it would be very much kind of you to fix the other issue I mentioned [here](https://github.com/yebekhe/SubConvertor/issues/4)

**Comment by yebekhe** [comment]
there will be no more support for clash configs, if you have solution you can fix and make pull request to the subconvertor repo 
thanks
