### ISSUE TITLE
معرفی کانال تلگرام

### ISSUE THREAD

**Issue by mshojaei77** [yebekhe/TelegramV2rayCollector#7]
https://t.me/V2RayTz
https://t.me/Hope_Net
https://t.me/Proxy_seven
https://t.me/vless_ir
https://t.me/vless_vmess
https://t.me/VmessProtocol
https://t.me/customv2ray
https://t.me/PrivateVPNs
https://t.me/NetAccount
https://t.me/beiten
https://t.me/webclub_team

**Comment by yebekhe** [comment]
تشکر ، اضافه شد

**Comment by Aitesla** [comment]
https://t.me/TheHotVPN

**Comment by coldwater-10** [comment]
https://t.me/ConfigsHUB

**Comment by EndermanCo** [comment]
سلام لطفا customv2ray را حذف کنید اکثر کانفیگاش دزدین و اسکین
@yebekhe
