### ISSUE TITLE
Problem with Sing-Box 1.8 and above,  cache_file and related fields in Clash API is deprecated in sing-box 1.8.0

### ISSUE THREAD

**Issue by Bijan-Pouya** [yebekhe/TelegramV2rayCollector#70]
the Error:

Service Error
(packet-tunnel) error: create service: create service: create clash api server: cache_file and related fields in Clash API is deprecated in sing-box 1.8.0, use experimental.cache_file instead.

The Migration Guide:
https://sing-box.sagernet.org/migration/

Please update configs for sing-box
Thanks in advance

**Comment by NekoHanaku** [comment]
use singbox sfasfi links like below
https://github.com/yebekhe/TelegramV2rayCollector/raw/main/singbox/sfasfi/mix.json
