### ISSUE TITLE
Empty sub files. No configs are in it.

### ISSUE THREAD

**Issue by AliAlmasi** [yebekhe/TelegramV2rayCollector#77]
take a look at one of the sub files

https://github.com/yebekhe/TelegramV2rayCollector/blob/main/sub%2Fnormal%2Fmix

full of emptiness 😅

it also has happened in every other sub files. check the files from the last commit.

**Comment by farshad-sadri** [comment]
Same issue here. Thanks. 🙏

**Comment by AliAlmasi** [comment]
@yebekhe would you please take a look?

This project is the only way we can connect to free Internet through ADSL (in my case, Shatel)

Warp and cf-workers barely work.
